# Generated by Django 5.0.4 on 2024-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell1DailyKwh',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('ups1_incm1', models.BigIntegerField(blank=True, db_column='ups1_incm1', null=True)),
                ('ups1_incm2', models.BigIntegerField(blank=True, db_column='ups1_incm2', null=True)),
                ('ups1_incm3', models.BigIntegerField(blank=True, db_column='ups1_incm3', null=True)),
                ('ups1_incm4', models.BigIntegerField(blank=True, db_column='ups1_incm4', null=True)),
                ('ups1_incm5', models.BigIntegerField(blank=True, db_column='ups1_incm5', null=True)),
                ('ups1_og1', models.BigIntegerField(blank=True, db_column='ups1_og1', null=True)),
                ('ups1_og2', models.BigIntegerField(blank=True, db_column='ups1_og2', null=True)),
                ('ups1_og3', models.BigIntegerField(blank=True, db_column='ups1_og3', null=True)),
                ('ups1_og4', models.BigIntegerField(blank=True, db_column='ups1_og4', null=True)),
                ('ups1_og5', models.BigIntegerField(blank=True, db_column='ups1_og5', null=True)),
                ('ups1_og_acb1', models.BigIntegerField(blank=True, db_column='ups1_og_acb1', null=True)),
                ('ups1_og_acb2', models.BigIntegerField(blank=True, db_column='ups1_og_acb2', null=True)),
                ('ups1_lt_pnl1', models.BigIntegerField(blank=True, db_column='ups1_lt_pnl1', null=True)),
                ('ups1_lt_pnl2', models.BigIntegerField(blank=True, db_column='ups1_lt_pnl2', null=True)),
                ('cell_lt_pnl1', models.BigIntegerField(blank=True, db_column='cell_lt_pnl1', null=True)),
                ('cell_lt_pnl2', models.BigIntegerField(blank=True, db_column='cell_lt_pnl2', null=True)),
                ('hwt1', models.BigIntegerField(blank=True, db_column='hwt1', null=True)),
            ],
            options={
                'db_table': 'cell1_daily_kwh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellLtPanel1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_lt_panel1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellLtPanel2Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_lt_panel2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hwt1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'hwt1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Incomer1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_incomer1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Incomer2Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_incomer2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Incomer3Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_incomer3_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Incomer4Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_incomer4_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Incomer5Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_incomer5_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1LtPanel1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_lt_panel1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1LtPanel2Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_lt_panel2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og2Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og3Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og3_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og4Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og4_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og5Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og5_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1OgAcb1Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og_acb1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1OgAcb2Data',
            fields=[
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og_acb2_data',
                'managed': False,
            },
        ),
    ]
