# Generated by Django 5.0.4 on 2024-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amf1DailyKwhAnomalies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('apfc2_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('tf2_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('dg2_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('og2_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('og1_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('dg1_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('tf1_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('apfc1_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Amf2DailyKwhAnomalies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('apfc4_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('tf4_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('dg4_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('og4_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('og3_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('dg3_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('tf3_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('apfc3_kwh_anomaly', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
