# Generated by Django 5.0.4 on 2024-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircomp1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'AIRCOMP1_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aircomp2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'AIRCOMP2_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aircomp3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'AIRCOMP3_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aircomp4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'AIRCOMP4_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChlTr2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'CHL_TR2_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenPdbData',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'GEN_PDB_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lamin3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'LAMIN3_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lamin4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'LAMIN4_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LightDbData',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'LIGHT_DB_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mod2DailyKwh',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('lamin4', models.BigIntegerField(blank=True, db_column='LAMIN4', null=True)),
                ('lamin3', models.BigIntegerField(blank=True, db_column='LAMIN3', null=True)),
                ('chill_tr2', models.BigIntegerField(blank=True, db_column='CHILL_TR2', null=True)),
                ('aircomp4', models.BigIntegerField(blank=True, db_column='AIRCOMP4', null=True)),
                ('aircomp3', models.BigIntegerField(blank=True, db_column='AIRCOMP3', null=True)),
                ('aircomp2', models.BigIntegerField(blank=True, db_column='AIRCOMP2', null=True)),
                ('aircomp1', models.BigIntegerField(blank=True, db_column='AIRCOMP1', null=True)),
                ('gen_pdb', models.BigIntegerField(blank=True, db_column='GEN_PDB', null=True)),
                ('lighting_db', models.BigIntegerField(blank=True, db_column='LIGHTING_DB', null=True)),
                ('ups_og1', models.BigIntegerField(blank=True, db_column='UPS_OG1', null=True)),
                ('ups_og2', models.BigIntegerField(blank=True, db_column='UPS_OG2', null=True)),
                ('ups_og3', models.BigIntegerField(blank=True, db_column='UPS_OG3', null=True)),
                ('ups_og4', models.BigIntegerField(blank=True, db_column='UPS_OG4', null=True)),
                ('ups_og5', models.BigIntegerField(blank=True, db_column='UPS_OG5', null=True)),
                ('ups_lt_og1', models.BigIntegerField(blank=True, db_column='UPS_LT_OG1', null=True)),
                ('ups_lt_og2', models.BigIntegerField(blank=True, db_column='UPS_LT_OG2', null=True)),
                ('ups_lt_og3', models.BigIntegerField(blank=True, db_column='UPS_LT_OG3', null=True)),
            ],
            options={
                'db_table': 'MOD2_DAILY_KWH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsLtOg1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_LT_OG1_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsLtOg2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_LT_OG2_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsLtOg3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_LT_OG3_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsOg1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_OG1_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsOg2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_OG2_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsOg3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_OG3_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsOg4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_OG4_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsOg5Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='DATE_TIME', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='AVG_VOLTAGE', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='AVG_CURRENT', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='KWH', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='KW', null=True)),
            ],
            options={
                'db_table': 'UPS_OG5_DATA',
                'managed': False,
            },
        ),
    ]
