# Generated by Django 5.0.4 on 2024-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmCantFeedData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'adm_cant_feed_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChilTr1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'chil_tr1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrechData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'crech_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralPdbData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'general_pdb_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HvacFeederData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'hvac_feeder_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lamin1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'lamin1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lamin2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'lamin2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LightingDbData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'lighting_db_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mod1DailyKwh',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('pcc2_incm', models.BigIntegerField(blank=True, db_column='pcc2_incm', null=True)),
                ('hvac', models.BigIntegerField(blank=True, db_column='hvac', null=True)),
                ('util_feed', models.BigIntegerField(blank=True, db_column='util_feed', null=True)),
                ('ups_incm1', models.BigIntegerField(blank=True, db_column='ups_incm1', null=True)),
                ('ups_incm2', models.BigIntegerField(blank=True, db_column='ups_incm2', null=True)),
                ('ups_incm3', models.BigIntegerField(blank=True, db_column='ups_incm3', null=True)),
                ('ups_incm4', models.BigIntegerField(blank=True, db_column='ups_incm4', null=True)),
                ('ups_incm5', models.BigIntegerField(blank=True, db_column='ups_incm5', null=True)),
                ('adm_cant_feed', models.BigIntegerField(blank=True, db_column='adm_cant_feed', null=True)),
                ('lighting_db', models.BigIntegerField(blank=True, db_column='lighting_db', null=True)),
                ('crech', models.BigIntegerField(blank=True, db_column='crech', null=True)),
                ('gen_pdb', models.BigIntegerField(blank=True, db_column='gen_pdb', null=True)),
                ('pcc1_incm', models.BigIntegerField(blank=True, db_column='pcc1_incm', null=True)),
                ('solar_feed', models.BigIntegerField(blank=True, db_column='solar_feed', null=True)),
                ('lamin1', models.BigIntegerField(blank=True, db_column='lamin1', null=True)),
                ('lamin2', models.BigIntegerField(blank=True, db_column='lamin2', null=True)),
                ('chill_tr1', models.BigIntegerField(blank=True, db_column='chill_tr1', null=True)),
            ],
            options={
                'db_table': 'mod1_daily_kwh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcc1IncmData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'pcc1_incm_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcc2IncmData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'pcc2_incm_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolarFeederData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'solar_feeder_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsIncm1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups_incm1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsIncm2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups_incm2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsIncm3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups_incm3_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsIncm4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups_incm4_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsIncm5Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups_incm5_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilFeedData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'util_feed_data',
                'managed': False,
            },
        ),
    ]
