# Generated by Django 5.0.4 on 2024-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellLtPanel1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_lt_panel1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellLtPanel2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_lt_panel2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellToolPdb1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_tool_pdb1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellToolPdb2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'cell_tool_pdb2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chiller2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'chiller2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcc1DailyKwh',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('chiller2', models.BigIntegerField(blank=True, db_column='chiller2', null=True)),
                ('cell_lt_pnl1', models.BigIntegerField(blank=True, db_column='cell_lt_pnl1', null=True)),
                ('cell_tool_pdb1', models.BigIntegerField(blank=True, db_column='cell_tool_pdb1', null=True)),
                ('pcc1_incm', models.BigIntegerField(blank=True, db_column='pcc1_incm', null=True)),
                ('ups1_og1', models.BigIntegerField(blank=True, db_column='ups1_og1', null=True)),
                ('ups1_og2', models.BigIntegerField(blank=True, db_column='ups1_og2', null=True)),
                ('ups1_og3', models.BigIntegerField(blank=True, db_column='ups1_og3', null=True)),
                ('ups1_og4', models.BigIntegerField(blank=True, db_column='ups1_og4', null=True)),
                ('ups1_og5', models.BigIntegerField(blank=True, db_column='ups1_og5', null=True)),
                ('pcc2_incm', models.BigIntegerField(blank=True, db_column='pcc2_incm', null=True)),
                ('cell_lt_pnl2', models.BigIntegerField(blank=True, db_column='cell_lt_pnl2', null=True)),
                ('cell_tool_pdb2', models.BigIntegerField(blank=True, db_column='cell_tool_pdb2', null=True)),
                ('ups2_og1', models.BigIntegerField(blank=True, db_column='ups2_og1', null=True)),
                ('ups2_og2', models.BigIntegerField(blank=True, db_column='ups2_og2', null=True)),
                ('ups2_og3', models.BigIntegerField(blank=True, db_column='ups2_og3', null=True)),
                ('ups2_og4', models.BigIntegerField(blank=True, db_column='ups2_og4', null=True)),
                ('ups2_og5', models.BigIntegerField(blank=True, db_column='ups2_og5', null=True)),
            ],
            options={
                'db_table': 'pcc1_daily_kwh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcc1IncomerData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'pcc1_incomer_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcc2IncomerData',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'pcc2_incomer_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og3_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og4_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups1Og5Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups1_og5_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups2Og1Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups2_og1_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups2Og2Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups2_og2_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups2Og3Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups2_og3_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups2Og4Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups2_og4_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ups2Og5Data',
            fields=[
                ('date_time', models.DateTimeField(db_column='date_time', primary_key=True, serialize=False)),
                ('avg_voltage', models.FloatField(blank=True, db_column='avg_voltage', null=True)),
                ('avg_current', models.BigIntegerField(blank=True, db_column='avg_current', null=True)),
                ('kwh', models.BigIntegerField(blank=True, db_column='kwh', null=True)),
                ('kw', models.IntegerField(blank=True, db_column='kw', null=True)),
            ],
            options={
                'db_table': 'ups2_og5_data',
                'managed': False,
            },
        ),
    ]
